##
## EPITECH PROJECT, 2022
## printf
## File description:
## compile_and_run_test.sh
##

bg="\033[1;40m"
ZERO="\033[30;${bg}"
ONE="\033[1;34m${bg}"
TWO="\033[1;32m${bg}"
THREE="\033[1;36m${bg}"
FOUR="\033[1;31m${bg}"
FIVE="\033[1;35m${bg}"
SIX="\033[1;33m${bg}"
SEVEN="\033[1;37m${bg}"
EIGHT="\033[1;90m${bg}"
NINE="\033[1;94m${bg}"
A="\033[1;92m${bg}"
B="\033[1;96m${bg}"
C="\033[1;91m${bg}"
D="\033[1;95m${bg}"
E="\033[1;93m${bg}"
F="\033[1;97m${bg}"
r="\033[1;0m${A}"

UNIT_TEST_FOLDER=tests
UNIT_TEST_FILE=test_my_printf.c

PROGRAM_FILE=libmy.a

CC=gcc

LIB_ACCESS=-L.\ -lmy

UNIT_BINARY_NAME=unit_tests
CFLAGS=-Wall\ -Wextra\ -lm
CPPFLAGS=-I./include
CRITERION_FLAGS=--coverage\ -lcriterion
TEST_PATH=$UNIT_TEST_FOLDER/$UNIT_TEST_FILE

UNWANTED_GUESTS=./*.gcda\ ./*.gcno

function display_help_p2() {
    echo -e ""
    echo -ne "It is recommended you add ${FIVE}this script${r} and "
    echo -e "${FOUR}'$UNIT_TEST_FILE'${r} to your ${SEVEN}.gitignore${r}."
    echo -ne "To add these files, ${THREE}create${r}/${SIX}open${r} a "
    echo -e "${SEVEN}.gitignore${r} file in the root of your repository."
    echo -e "Make sure the following lines are present: ${D}"
    echo "$UNIT_BINARY_NAME"
    echo "$0"
    echo "$UNIT_TEST_FILE"
    echo "$PROGRAM_FILE"
    echo "*.gcda"
    echo "*.gcno"
    echo ""
    echo -e "${r}If these lines are present, then you are set to go."
}

function display_help_p1() {
    echo -ne "${r}This program is ment to compile a unit-test file with a "
    echo -e "${THREE}$PROGRAM_FILE${r}"
    echo -e "The ${THREE}$PROGRAM_FILE${r} will be generated by the makefile "
    echo -e "located in the same folder as this script."
    echo -ne "The test file will be found in the folder ${FOUR}"
    echo -e "'$UNIT_TEST_FOLDER'${r}."
    echo -ne "The name of the file must be ${FOUR}'$UNIT_TEST_FILE'${r} and it "
    echo -e "must be located in ${FOUR}'$UNIT_TEST_FOLDER'${r}."
    echo -ne "In order to run the test, you just need to ${THREE}meet the below"
    echo -ne " requirements${r} before calling this file without ${SIX}any "
    echo -e "options${r}."
    echo -e "${SEVEN}These are the following requirements:${r}"
    echo -ne "- Your makefile, when called the following way ${SEVEN}'make'${r}"
    echo -e " should output a file name ${THREE}'$PROGRAM_FILE'${r} wich should"
    echo -e "  be located in the same folder as this script."
    echo -ne "- Your makefile should contain the ${SEVEN}clean${r}, "
    echo -e "${SEVEN}fclean${r} and ${SEVEN}re${r} rules."
    display_help_p2
}

function disclaimer() {
    echo -e "${SIX}!!${C} Disclaimer ${SIX}!!${r}"
    echo -e "${THREE}This program is provided as if and without any warranty."
    echo -e "${B}Use at your own risk!${r}\n"
}

function compile_n_run() {
    echo -e "${FOUR}Compiling program ...${r}"
    make re
    echo -e "${THREE}Compiling tests ...${r}"
    ${CC} -o ${UNIT_BINARY_NAME} ${CFLAGS} ${CPPFLAGS} ${TEST_PATH} ${LIB_ACCESS} ${CRITERION_FLAGS}
    echo -e "${FIVE}Running tests ...${r}"
    ./$UNIT_BINARY_NAME
    echo -e "${SEVEN}Cleaning up files...${r}"
    rm -f $UNWANTED_GUESTS
    echo -e "${NINE}All done."
}

echo -e "${r}${SIX}(c) Written by Henry Letellier"
disclaimer
if [ $# -gt 0 ]
then
    display_help
else
    compile_n_run
fi
echo -e "\033[0;0m"
echo "End Of Script"
